version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootchat123456
      MYSQL_PASSWORD: chat123456
      MYSQL_DATABASE: chat-app
      MYSQL_USER: chatapp_user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql: